### ISSUE TITLE
[Domain Proposal] I offer the svg-cg.org Domain free of charge based on Non-Profit Community use only

### ISSUE THREAD

**Issue by robin-rpr** [svg-cg/svg-cg.github.io#1]
Hello folks,

I parked the `svg-cg.org` Domain and wanted to offer the Community Chair the free (Non-Profit only) ability to use it for the `svg-cg.github.io` page as well as for permanent E-Mail forwarding.

Current E-Mail Forwards:
ameliabr@svg-cg.org | amelia.bellamy.royds@gmail.com

On agreement, I will continue the full ownership and management of the Domain under my Name and will make sure to either hand over the Transfer-Token 3 months before expiration or delete the Domain permanently before ending my SVG Community Group Membership.

If you are a Community Member and want to appeal against this proposal, feel free to reach out via our public Community Group Email List or directly below this Github Issue.

Kind regards,
Robin R.

**Comment by AmeliaBR** [comment]
Hi Robin,

Thanks! It would be nice to have stable URLs that are independent of the _github.io_ domain.

I'm interested to know if any other group members have opinions on how best to manage the domain & emails, maybe from experience with other open-source projects.

E.g., for emails, I know W3C has standard emails for _working_ groups that forward to the current chairs, although I don't think they currently set up the same addresses for community groups. Something like that might be better than an address tied specifically to my name.

**Comment by robin-rpr** [comment]
Hey Amelia,

Thanks for your feedback! I have, as requested above, setup a chair@svg-cg.org email which forwards incoming emails to the current SVG Community Group Chairs :)

> I'm interested to know if any other group members have opinions on how best to manage the domain & emails, maybe from experience with other open-source projects.

Based on the [Core Node.js Working Groups](https://nodejs.org/en/about/working-groups), it would be practical to have a dedicated "Website"-Team which purpose is to build and maintain the public website and domain for the SVG Community Group.

**Comment by robin-rpr** [comment]
@AmeliaBR As per [charter/#decision](https://svg-cg.github.io/charter/#decision) a poll or reply decision process with explicit date might be required at this point.

**Comment by AmeliaBR** [comment]
Thanks for the prompting, Robin. Sorry I haven't been a very active chair lately, but no one needs to wait for me to get things done!

Everyone, please indicate support with a :+1: on Robin's comment.  If you have an objection, it would be helpful if you leave a comment explaining why.

**Comment by BigBadaboom** [comment]
I have no problem with this.  My only question would be whether the W3C has any policies regarding W3C-related activities using private domains?

**Comment by AmeliaBR** [comment]
> My only question would be whether the W3C has any policies regarding W3C-related activities using private domains?

Maybe @svgeesus has details on the policy, but many W3C working groups maintain their own domains for hosting editor's drafts.  And the community group is even less of an ”official W3C activity” than a working group.

**Comment by svgeesus** [comment]
We already have things like [csswg.org](http://wiki.csswg.org) and [svg.org](svg.org) so there is ample precedent for such domains.

**Comment by AmeliaBR** [comment]
Robin & I got this set up today. Welcome to https://svg-cg.org/ !
